apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-tans-app
  labels:
    app: flash-tans
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash-tans
  template:
    metadata:
      labels:
        app: flash-tans
    spec:
      containers:
        - name: flash-tans
          image: josephmaina/flash-tans-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: PORT
              value: "3000"
            - name: MONGO_URI
              value: "mongodb://mongodb-0.mongodb-service:27017,mongodb-1.mongodb-service:27017,mongodb-2.mongodb-service:27017/flash_tans?replicaSet=rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: flash-tans-service
spec:
  type: NodePort
  selector:
    app: flash-tans
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
