apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-0
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-1
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-2
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-2"
